# Generated by Django 3.2.6 on 2021-08-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='job',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('Engineering', 'Engineering'), ('Jurist', 'Jurist'), ('Economist', 'Economist'), ('Doctor', 'Doctor')], max_length=30, null=True),
        ),
    ]
